//
// Generated file, do not edit! Created by nedtool 5.3 from Volt.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CONGESTIONWINDOW_H
#define __CONGESTIONWINDOW_H

#include <omnetpp.h>
#include "EventTimeout.h"

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// Que el emisor sepa distinguir
// [(state, timer), , ]
// TODO: Ernesto
class CongestionWindow {
private:
	int maxSize = 2147483647;
	int size;
	int msgSendingAmount = 0;
	EventTimeout * window[2147483647];  // INT_MAX
public:
	CongestionWindow();
    virtual ~CongestionWindow();

    /* Tamaño actual de la ventana de congestión */
    int getSize();

    /* Dado el tamaño de la ventana y cuanto ya está ocupada
     * devuelve la cantidad de mensajes que se pueden agregar */
	int getAvailableWin();

	/* Setea el tamaño de la ventana de congestión */
	void setSize(int newSize);

	/* Agrega un evento que representa que un mensaje fue enviado y está
	 * en la sub red. */
	void addTimeoutMsg(int seqN, EventTimeout * msg);

	/* Quita un mensaje de la ventana de congestión y lo devuelve */
	EventTimeout * popTimeoutMsg(int seqN);
protected:
	//
};

#endif // ifndef __CONGESTIONWINDOW_H

