//
// Generated file, do not edit! Created by nedtool 5.3 from EventTimeout.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __EVENTTIMEOUT_H
#define __EVENTTIMEOUT_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>EventTimeout.msg:2</tt> by nedtool.
 * <pre>
 * message EventTimeout
 * {
 *     int seqN;
 * }
 * </pre>
 */
class EventTimeout : public ::omnetpp::cMessage
{
  protected:
    int seqN;

  private:
    void copy(const EventTimeout& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const EventTimeout&);

  public:
    EventTimeout(const char *name=nullptr, short kind=0);
    EventTimeout(const EventTimeout& other);
    virtual ~EventTimeout();
    EventTimeout& operator=(const EventTimeout& other);
    virtual EventTimeout *dup() const override {return new EventTimeout(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSeqN() const;
    virtual void setSeqN(int seqN);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EventTimeout& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EventTimeout& obj) {obj.parsimUnpack(b);}


#endif // ifndef __EVENTTIMEOUT_H

